# Generated by Django 2.2.14 on 2021-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackages',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='purchasedpackages',
            name='percent10',
        ),
        migrations.RemoveField(
            model_name='purchasedpackages',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='purchasedpackages',
            name='total_income',
        ),
        migrations.AddField(
            model_name='purchasedpackages',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
