# Generated by Django 2.2.14 on 2021-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackages',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
