# Generated by Django 3.1 on 2021-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210516_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='available_fund',
            field=models.FloatField(default=0),
        ),
    ]
