# Generated by Django 3.1 on 2021-07-03 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210517_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allroionroiincome',
            name='level',
        ),
        migrations.AlterField(
            model_name='purchasedpackages',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
