# Generated by Django 3.1 on 2021-07-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20210713_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(blank=True, max_length=300, null=True)),
                ('link2', models.CharField(blank=True, max_length=300, null=True)),
                ('link3', models.CharField(blank=True, max_length=300, null=True)),
                ('link4', models.CharField(blank=True, max_length=300, null=True)),
                ('link5', models.CharField(blank=True, max_length=300, null=True)),
                ('link6', models.CharField(blank=True, max_length=300, null=True)),
                ('link7', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('linkClicked', models.ManyToManyField(to='api.Links')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
