# Generated by Django 3.1 on 2021-07-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210714_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
