# Generated by Django 3.1 on 2021-07-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('linkClicked', models.ManyToManyField(to='api.Links')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchasedpackages')),
            ],
        ),
    ]
