# Generated by Django 3.1 on 2021-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackages',
            name='clickedLinks',
            field=models.IntegerField(default=0),
        ),
    ]
