# Generated by Django 3.1 on 2021-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_withdrawal_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelincome',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
